"""
mailer.py

Sends email notifications for newly added tenders.
"""

from collections import defaultdict
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from config import (
    EMAIL_SENDER,
    EMAIL_PASSWORD,
    EMAIL_RECEIVER,
    SMTP_SERVER,
    SMTP_PORT,
    logger,
)


class TenderMailer:

    def __init__(self):

        self.sender = EMAIL_SENDER
        self.password = EMAIL_PASSWORD

        self.receivers = [
            email.strip()
            for email in EMAIL_RECEIVER.split(",")
            if email.strip()
        ]

    # --------------------------------------------------------

    def build_html(self, tenders):

        grouped = defaultdict(list)

        for tender in tenders:
            grouped[tender.get("Source", "Unknown")].append(tender)

        html = f"""
        <html>

        <body style="font-family:Arial;">

        <h2>SPMCIL Tender Alert</h2>

        <p>
        <b>Total Matching Tenders : {len(tenders)}</b>
        </p>

        <hr>
        """

        for source, source_tenders in grouped.items():

            html += f"""
            <h3 style="
                background:#2F5597;
                color:white;
                padding:10px;
                border-radius:4px;
                margin-top:20px;
                margin-bottom:8px;
            ">
                🏢 {source}
                &nbsp;
                <span style="
                    background:white;
                    color:#2F5597;
                    padding:3px 8px;
                    border-radius:12px;
                    font-size:12px;
                    font-weight:bold;
                ">
                    {len(source_tenders)} Tender(s)
                </span>
            </h3>

            <table border="1"
                cellspacing="0"
                cellpadding="6"
                style="border-collapse:collapse;
                        width:100%;
                        margin-bottom:25px;
                        font-size:13px;">

                <tr style="background:#D9EAD3;">

                    <th>Tender Number</th>

                    <th>Tender Title</th>
                    
                    <th>Keyword</th>

                    <th>Publishing Date</th>

                    <th>Closing Date</th>
                    
                    <th>Status</th>
                    
                    <th>Days Left</th>

                    <th>Tender Document</th>

                    <th>Corrigendum</th>

                </tr>
            """

            for tender in source_tenders:

                tender_doc = "-"

                if tender.get("Tender Document URL"):

                    tender_doc = f"""
                    <a href="{tender['Tender Document URL']}">
                        Download
                    </a>
                    """

                corrigendum = "-"

                if tender.get("Corrigendum URL"):

                    corrigendum = f"""
                    <a href="{tender['Corrigendum URL']}">
                        View
                    </a>
                    """

                html += f"""
                <tr>

                    <td>{tender.get('Tender Number','')}</td>

                    <td>{tender.get('Tender Title','')}</td>
                    
                    <td>{tender.get('Matched Keyword','')}</td>

                    <td>{tender.get('Publishing Date','')}</td>

                    <td>{tender.get('Closing Date','')}</td>
                    
                    <td>{tender.get('Status', '')}</td>
                    
                    <td>{tender.get('Days Left', '')}</td>

                    <td align="center">{tender_doc}</td>

                    <td align="center">{corrigendum}</td>

                </tr>
                """

            html += "</table>"

        html += """

        <hr>

        <p style="font-size:12px;color:gray;">

        This is an automated email generated by the
        <b>SPMCIL Tender Monitoring System</b>.

        </p>

        </body>

        </html>
        """

        return html

    # --------------------------------------------------------

    def send_email(self, tenders):

        if not tenders:

            logger.info("No keyword matched tenders.")

            print("No email sent.")

            return

        try:

            message = MIMEMultipart("alternative")

            message["Subject"] = (
                f"SPMCIL Tender Alert ({len(tenders)} New Tender(s))"
            )

            message["From"] = self.sender

            message["To"] = ", ".join(self.receivers)

            html = self.build_html(tenders)

            message.attach(
                MIMEText(html, "html")
            )

            server = smtplib.SMTP(
                SMTP_SERVER,
                SMTP_PORT
            )

            server.starttls()

            server.login(
                self.sender,
                self.password
            )

            server.sendmail(
                self.sender,
                self.receivers,
                message.as_string()
            )

            server.quit()

            logger.info("Email sent successfully.")

            print("Email sent successfully.")

        except Exception as e:

            logger.exception(e)

            print(e)